### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by Jalilimm** [kostecky/VBT-Barbell-Tracker#1]
I want to conduct a reliability and validity research for this project for my thesis. I need to contact you. Could you please provide me your email address to discuss a private matter? Many thanks.

**Comment by kostecky** [comment]
If you provide your e-mail address on your github profile I can contact you.

**Comment by simonwilken** [comment]
@Jalilimm ihm writing a paper about the same topic. could I read your thesis about reliability and validity?
